/* 14.Write a function that takes an array of objects same as the object in question no.
13 but should contain unique objects only and sort_order
(descending/ascending) as arguments and sorts the objects based on property
fullName.
 */



let object = [ { _id: 1,
    fullName: 'Aayush Adeshara',
    profileImage: 'users/1.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'aayush.adeshara@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'ubuntu 21.10 Windows 11' },
  { _id: 2,
    fullName: 'Akshit Modi',
    profileImage: 'users/2.png',
    highestQualification_PassoutYear: 'B.E IT - 2022',
    emailId: 'akshit.modi@bacancy.com',
    technologyAssigned: 'DevOps',
    os: 'Ubuntu 20.04' },
  { _id: 3,
    fullName: 'Apexa Patel',
    profileImage: 'users/3.png',
    highestQualification_PassoutYear: 'B.E(IT) - 2022',
    emailId: 'apexa.patel@bacancy.com',
    technologyAssigned: 'NodeJS',
    os: 'Windows 10' },
  { _id: 4,
    fullName: 'Bhargav Dobariya',
    profileImage: 'users/4.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'bhargav.dobariya@bacancy.com',
    technologyAssigned: 'Flutter',
    os: 'ubuntu 20.04' },
  { _id: 5,
    fullName: 'Chetan Punani',
    profileImage: 'users/5.png',
    highestQualification_PassoutYear: 'M.E - 2022',
    emailId: 'chetan.punani@bacancy.com',
    technologyAssigned: 'VueJS',
    os: 'ubuntu 20.04' },
  { _id: 6,
    fullName: 'Dhruval Mayavanshi',
    profileImage: 'users/6.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'dhruval.mayavanshi@bacancy.com',
    technologyAssigned: 'UI/UX',
    os: 'windows 11' },
  { _id: 7,
    fullName: 'Divyansh Bhatnagar',
    profileImage: 'users/7.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2021',
    emailId: 'divyansh.bhatnagar@bacancy.com',
    technologyAssigned: 'ReactNative',
    os: 'Windows 10' },
  { _id: 8,
    fullName: 'Ishita Shah',
    profileImage: 'users/8.png',
    highestQualification_PassoutYear: 'B.E(IT) - 2022',
    emailId: 'ishita.shah@bacancy.com',
    technologyAssigned: 'Vue JS',
    os: 'Windows 11' },
  { _id: 9,
    fullName: 'Jaykumar Bhatt',
    profileImage: 'users/9.png',
    highestQualification_PassoutYear: 'B.Tech. - 2022',
    emailId: 'jaykumar.bhatt@bacancy.com',
    technologyAssigned: 'NodeJS',
    os: 'ubuntu 20.04 Windows 10' },
  { _id: 10,
    fullName: 'Jemis Maru',
    profileImage: 'users/10.png',
    highestQualification_PassoutYear: 'B.E. - 2022',
    emailId: 'jemis.maru@bacancy.com',
    technologyAssigned: 'VueJS',
    os: 'windows 10' },
  { _id: 11,
    fullName: 'Kalpin Gajjar',
    profileImage: 'users/11.png',
    highestQualification_PassoutYear: 'B.E(CE) - 2022',
    emailId: 'kalpin.gajjar@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'Windows 10' },
  { _id: 12,
    fullName: 'Khushbu Rajgor',
    profileImage: 'users/12.png',
    highestQualification_PassoutYear: 'MCA - 2022',
    emailId: 'khushbu.rajgor@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'ubuntu 20.04 Windows' },
  { _id: 13,
    fullName: 'Krushit Dudhat',
    profileImage: 'users/13.png',
    highestQualification_PassoutYear: 'B.E - 2022',
    emailId: 'krushit.dudhat@bacancy.com',
    technologyAssigned: 'NodeJS',
    os: 'Windows 10 Ubuntu' },
  { _id: 14,
    fullName: 'Lav Panchal',
    profileImage: 'users/14.png',
    highestQualification_PassoutYear: 'Msc.(CA&IT) - 2022',
    emailId: 'lav.panchal@bacancy.com',
    technologyAssigned: 'NodeJS',
    os: 'Windows 10' },
  { _id: 15,
    fullName: 'Manish Rathod',
    profileImage: 'users/15.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'manish.rathod@bacancy.com',
    technologyAssigned: 'NodeJs',
    os: 'windows' },
  { _id: 16,
    fullName: 'Meet Acharya',
    profileImage: 'users/16.png',
    highestQualification_PassoutYear: 'M.C.A - 2022',
    emailId: 'meet.acharya@bacancy.com',
    technologyAssigned: 'ReactJS',
    os: 'Windows 11' },
  { _id: 17,
    fullName: 'Mohit Shah',
    profileImage: 'users/17.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'mohit.shah@gmail.com',
    technologyAssigned: 'VueJS',
    os: 'Windows 10' },
  { _id: 18,
    fullName: 'Pranav Dodiya',
    profileImage: 'users/18.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'pranav.dodiya@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'Windows' },
  { _id: 19,
    fullName: 'Priyanka Manna',
    profileImage: 'users/19.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'priyanka.manna@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'Windows' },
  { _id: 20,
    fullName: 'Rahul Shah',
    profileImage: 'users/20.png',
    highestQualification_PassoutYear: 'MSc(CA&IT) - 2022',
    emailId: 'rahul.shah@bacancy.con',
    technologyAssigned: 'UI/UX Designer',
    os: 'Windows 11' },
  { _id: 21,
    fullName: 'Raj Panchal',
    profileImage: 'users/21.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'raj.panchal@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'windows' },
  { _id: 22,
    fullName: 'Rohan Deshpande',
    profileImage: 'users/22.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'Rohan.Deshpande@bacancy.com',
    technologyAssigned: 'ReactJS',
    os: 'windows' },
  { _id: 23,
    fullName: 'Rutvik Patel',
    profileImage: 'users/23.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2022',
    emailId: 'rutvik.patel@bacancy.com',
    technologyAssigned: 'VueJS',
    os: 'ubuntu 18' },
  { _id: 24,
    fullName: 'Smit Akhani',
    profileImage: 'users/24.png',
    highestQualification_PassoutYear: 'B.E. CE - 2022',
    emailId: 'smit.akhani@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'Windows 11' },
  { _id: 25,
    fullName: 'Sumit Kadiya',
    profileImage: 'users/25.png',
    highestQualification_PassoutYear: 'B.E. CE - 2021',
    emailId: 'sumit.kadiya@bacancy.com',
    technologyAssigned: 'React JS',
    os: 'Windows' },
  { _id: 26,
    fullName: 'Vaisvik Chaudhary',
    profileImage: 'users/26.png',
    highestQualification_PassoutYear: 'B.E/B.Tech. - 2021',
    emailId: 'vaisvik.chaudhary@bacancy.com ',
    technologyAssigned: 'ROR',
    os: 'Windows' },
  { _id: 27,
    fullName: 'Vinayak Chavan',
    profileImage: 'users/27.png',
    highestQualification_PassoutYear: 'B.E IT - 2022',
    emailId: 'vinayak.chavan@bacancy.com',
    technologyAssigned: 'NodeJS',
    os: 'Windows 10' },
  { _id: 28,
    fullName: 'Vinayak Varsani',
    profileImage: 'users/28.png',
    highestQualification_PassoutYear: 'B.E CSE - 2022',
    emailId: 'vinayak.varsani@bacancy.com',
    technologyAssigned: 'ROR',
    os: 'Windows 11' } ];


const arrSort = (arrOfObj, order) => {
    if(order !== "desc" && order !== "asc"){
        console.log("give order of sorting desc//asc /n array will by default in asc order");
    }
    arrOfObj.sort((a,b) => {
        let nameA = a.fullName.toUpperCase();
        let nameB = b.fullName.toUpperCase();
        if(nameA < nameB){
            return order === "desc" ? 1 : -1;
        }
        if(nameA > nameB){
            return order === "desc" ? -1 : 1;
        }
        return 0;
    });
    return arrOfObj;
}
console.log(arrSort(object, "desc"));